#+TITLE: ОРГАНИЗАЦИЯ ДИАЛОГА С ПОЛЬЗОВАТЕЛЕМ В MATLAB. ФОРМАТИРОВАННЫЙ ВЫВОД
#+LANGUAGE: ru
#+AUTHOR: В.Д. Панков
#+OPTIONS: toc:nil
#+DEPARTMENT: КАФЕДРА №43
#+TEACHER: М.В. Величко
#+COURSE: Информатика
#+TYPE: ОТЧЕТ О ЛАБОРАТОРНОЙ РАБОТЕ №4
* Выполнение индивидуального задания

Цель: Знакомство с особенностями ввода и вывода данных
в MATLAB, организацией диалога с пользователем,
проверки введенных пользователем данных.
Организация форматированного вывода результатов расчета.
Закрепление навыков по преобразованию типов данных,
организации программ-сценариев и подпрограмм.


Задание №1
Написать функцию, которая запросит у пользователя данное, проверит,
удовлетворяет ли введенное данное условию, приведенному в таблице 4
(условие 1 согласно номеру варианта). Если введенное пользователем
значение не удовлетворяет условию, функция выведет сообщение об
ошибке, предложит заново ввести данное. Последнее действие должно выполняться,
пока не будет осуществлен корректный ввод данного.
Входным параметром функции является строка, которая будет выведена при
запросе на ввод числа. Выходным параметром является корректное данное
(удовлетворяющее условию 1). Функция должна быть задокументирована. 


